### ISSUE TITLE
PHP 5.5 will deprecate MySQL functions currently in use; Pear_Error also to be deprecated

### ISSUE THREAD

**Issue by registrobr** [registrobr/whmcs-registrobr-epp#26]
http://php.net/manual/en/migration55.deprecated.php

**Comment by registrobr** [comment]
PHP 5.4 already complains about some of the issues:
Strict Standards: Non-static method PEAR::isError() should not be called statically in /home/super/public_html/home/modules/registrars/registrobr/Net/EPP/Protocol.php on line 73

Strict Standards: Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in/home/super/public_html/home/modules/registrars/registrobr/RegistroEPP/RegistroEPP.class.php on line 172

Strict Standards: Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /home/super/public_html/home/modules/registrars/registrobr/Net/EPP/Client.php on line 112

Strict Standards: Non-static method PEAR::isError() should not be called statically in /home/super/public_html/home/modules/registrars/registrobr/Net/EPP/Protocol.php on line 73

Strict Standards: Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /home/super/public_html/home/modules/registrars/registrobr/Net/EPP/Client.php on line 112

Strict Standards: Non-static method PEAR::isError() should not be called statically in /home/super/public_html/home/modules/registrars/registrobr/Net/EPP/Protocol.php on line 73

**Comment by registrobr** [comment]
Perhaps the changes already made at https://gitlab.centralnic.com/centralnic/php-epp/tree/master/Net/EPP solve the mentioned issues

**Comment by registrobr** [comment]
WHMCS v6 will support PHP 5.5+, so WHMCS v6 interoperability (besides possible registrar module issues yet to be known) might also require moving out of deprecated functions.

**Comment by rubenskuhl** [comment]
WHMCS Version 6.0 supports PHP 5.3.7 or later, including PHP 5.4, 5.5 and 5.6.

**Comment by rubenskuhl** [comment]
WHMCS Version 6.0 requires PHP Database Extension	PDO

**Comment by rubenskuhl** [comment]
mysql_* functions that were removed still present in the code

**Comment by rubenskuhl** [comment]
Commit df07b5d replaced all database functions with Capsule calls. New table layout defined.
