### ISSUE TITLE
Use PHP 5.3+ IDN funcion

### ISSUE THREAD

**Issue by registrobr** [registrobr/whmcs-registrobr-epp#38]
PHP 5.3+ has functions to do IDN conversion; using instead of library simplifies distribution. 

http://www.php.net/manual/en/function.idn-to-utf8.php

**Comment by registrobr** [comment]
It also possible interacts with issue #51

**Comment by rubenskuhl** [comment]
WHMCS 6.0 already makes PHP 5.3.7+ a requirement.

**Comment by rubenskuhl** [comment]
PHP version requirement should also be tested in install script.

**Comment by rubenskuhl** [comment]
IDN libraries are not included by default. Will leave the add-on as is in order to not generate an additional install requirement.
