### ISSUE TITLE
Virtual Server VMWARE

### ISSUE THREAD

**Issue by hschiavo** [registrobr/whmcs-registrobr-epp#46]
Hello,
Is there any VMWARE virtual server that facilitates server installation?

Regards,
Henrique Schiavo

**Comment by registrobr** [comment]
It's not possible to build a virtual server image, since it would also contain the LAMP stack and WHMCS at specific versions that might not be the versions that suit an user needs. 

What could ease up installation is for WHMCS.com to bundle this module in the install package in the future.
