### ISSUE TITLE
Fatal error: cannot use string offset as array in /home/<something>/admin/configregistrars.php on line 0

### ISSUE THREAD

**Issue by registrobr** [registrobr/whmcs-registrobr-epp#47]
From PDH:
http://portaldohost.com.br/forum/uploads/monthly_11_2014/post-17290-0-57274700-1415741054.png

**Comment by rubenskuhl** [comment]
Image not available anymore, but error happened at one user installation

**Comment by rubenskuhl** [comment]
Unable to reproduce.
