### ISSUE TITLE
Uncaught exception while updating DNS servers

### ISSUE THREAD

**Issue by registrobr** [registrobr/whmcs-registrobr-epp#48]
Fatal error: Uncaught exception 'Exception' with message 'Falha ao alterar servidores DNS código 2308: mensagem 'Violação na política de gerência de dados' motivo 'Consulta recusada'' in /home/rave/public_html/central/modules/registrars/registrobr/RegistroEPP/RegistroEPPDomain.class.php:108 Stack trace: #0 /home/rave/public_html/central/modules/registrars/registrobr/registrobr.php(324): RegistroEPPDomain->updateNameServers(Array, Array) #1 /home/rave/public_html/central/includes/classes/WHMCS/Module.php(0): registrobr_SaveNameservers(Array) #2 /home/rave/public_html/central/includes/classes/WHMCS/Module/Registrar.php(0): WHMCS_Module->call() #3 /home/rave/public_html/central/includes/classes/WHMCS/Domains.php(0): WHMCS_Module_Registrar->call() #4 /home/rave/public_html/central/admin/clientsdomains.php(0): WHMCS_Domains->moduleCall() #5 {main} Next exception 'Exception' with message 'Falha ao alterar servidores DNS código 2308: mensagem 'Violação na política de gerência de dados' motivo 'Consulta recusada'' in /home/rave/public_html/central/includes/classes/WHMCS/Terminus.php on line 0

**Comment by registrobr** [comment]
From another issue:

Fatal error: Uncaught exception 'Exception' with message 'Falha ao alterar servidores DNS código 2303: mensagem 'Objeto não existe'' in /var/www/whmcs/modules/registrars/registrobr/RegistroEPP/RegistroEPPDomain.class.php:108 Stack trace: #0 /var/www/whmcs/modules/registrars/registrobr/registrobr.php(324): RegistroEPPDomain->updateNameServers(NULL, Array) #1 /var/www/whmcs/includes/classes/WHMCS/Module.php(0): registrobr_SaveNameservers(Array) #2 /var/www/whmcs/includes/classes/WHMCS/Module/Registrar.php(0): WHMCS_Module->call() #3 /var/www/whmcs/includes/classes/WHMCS/Domains.php(0): WHMCS_Module_Registrar->call() #4 /var/www/whmcs/admin/clientsdomains.php(0): WHMCS_Domains->moduleCall() #5 {main} Next exception 'Exception' with message 'Falha ao alterar servidores DNS código 2303: mensagem 'Objeto não existe'' in /var/www/whmcs/includes/classes/WHMCS/Terminus.php:0 Stack trace: #0 /var/www/whmcs/includes/classes/WHMCS/Terminus.php(0): WHMCS_Terminus::whmcsExceptionHandler() #1 [internal function]: WHMCS_Terminus in /var/www/whmcs/includes/classes/WHMCS/Terminus.php on line 0

**Comment by rubenskuhl** [comment]
Uncaught Exception can also be triggered by updating a domain no longer under registrar administration:

Fatal error: Uncaught exception 'Exception' with message 'Falha ao
alterar servidores DNS código 2201: mensagem 'Erro de autorização'' in
modules/registrars/registrobr/RegistroEPP/RegistroEPPDomain.class.php:108 Stack
trace: #0 registrars/registrobr/registrobr.php(324):
RegistroEPPDomain->updateNameServers(Array, Array) #1
includes/classes/class.module.php(0): registrobr_SaveNameservers(Array)
#2 includes/classes/class.domains.php(0): WHMCS_Module->call() #3
clientsdomains.php(0): WHMCS_Domains->moduleCall() #4 {main} thrown in
modules/registrars/registrobr/RegistroEPP/RegistroEPPDomain.class.php on
line 108

**Comment by rubenskuhl** [comment]
This issue referred to old code not currently in use.
