### ISSUE TITLE
DNS server update of tickets is to be allowed

### ISSUE THREAD

**Issue by registrobr** [registrobr/whmcs-registrobr-epp#50]
"Falha na Alteração no Servidor DNS
Modificação de dados de contato de domínios que ainda não completaram o ciclo de registro não é permitida em domínios .br"

Update of DNS servers can't be blocked as they are required to complete the registration cycle. Non-object version of module had this functionality.

**Comment by rubenskuhl** [comment]
Alterado para usar sempre DNS autoritativo *.auto.dns.br na criação do domínio, evitando pendência de DNS no domínio.
