### ISSUE TITLE
Possibility of obtaining CPF/CNPJ from a domain field instead of customer field

### ISSUE THREAD

**Issue by rubenskuhl** [registrobr/whmcs-registrobr-epp#64]
Some installations prefer obtaining CPF/CNPJ from a domain field instead of a customer field

**Comment by jozephbrasil** [comment]
This is required to force registro.br domain module to use the logic of system, allowing it to be compatible with others addons.

**Comment by rubenskuhl** [comment]
Newer versions of WHMCS seem to be going to the domain field direction instead of customer field.

**Comment by rubenskuhl** [comment]
v7 will only use domain field.

**Comment by rubenskuhl** [comment]
v8 will only use domain field
