### ISSUE TITLE
Error in argument 1, char 2: option not found r "crontabtmp.txt":18: bad minute

### ISSUE THREAD

**Issue by hypersize** [registrobr/whmcs-registrobr-epp#65]
Error in argument 1, char 2: option not found r
"crontabtmp.txt":18: bad minute
errors in crontab file, can't install.

help.

**Comment by hypersize** [comment]
php -v
Se seu php for versão 5.5 acima.
nano install.sh
Localize "** php -r **" troque por "** php5-cli -r **"
Ninguem ajudou, mas ta blz, segue ai minha contribuição.

**Comment by rubenskuhl** [comment]
Thanks, the only possible issue is whether php5-cli exists in installations with multiple PHP versions.
