### ISSUE TITLE
Set Environment Production

### ISSUE THREAD

**Issue by scarniel** [registrobr/whmcs-registrobr-epp#66]
In the file brdomaincheck.php exists the function:

function get_server() {
    include "configuration.php";

```
try {
    $link = mysqli_connect($db_host, $db_username, $db_password, $db_name);
    $query = "SELECT * FROM tblregistrars where registrar = 'registrobr' and setting = 'TestMode'";
    $result = $link->query($query);

    # se existe testmode entao vamos pro servidor de teste
    if (mysqli_num_rows($result) > 0) {
        return REGISTROBR_SERVER_TESTE;
    }
} catch (Exception $e) {
    die("error connection database");
}

return REGISTROBR_SERVER_PRODUCAO;
```

}

In the running version 6.2, when saving the data properties are encrypted in the database, ie there will be a record for the TestMode property even being "false".
In this case, it will return a record for the query and not even be labeled the property will always be in the "TestMode" option.
See below:
        # se existe testmode entao vamos pro servidor de teste
        if (mysqli_num_rows($result) > 0) {
            return REGISTROBR_SERVER_TESTE;
        }

**Comment by rubenskuhl** [comment]
For now we will try working with two branches instead of having it as a runtime option. Will see if that strategy works better or not in the longterm.

**Comment by rubenskuhl** [comment]
New module version will attempt to address both OT&E and production in a single branch.

**Comment by rubenskuhl** [comment]
It should be resolved, needs testing

**Comment by rubenskuhl** [comment]
Seems good.
