### ISSUE TITLE
WHMCS has updated PHP version requirements

### ISSUE THREAD

**Issue by rubenskuhl** [registrobr/whmcs-registrobr-epp#68]
Current supported PHP versions for WHMCS are 5.4 to 5.6; module doesn't work correctly with 5.6. 
From WHMCS: "The PHP 5.5 branch no longer receives regular bug fixes and will only receive critical security updates until it reaches its end of life. We recommend updating to a supported PHP version. Please see http://php.net/supported-versions.php"

PHP 5.4 should be the new version requirement for the time being, with compatibility with at least 5.5 and 5.6 a requirement.

**Comment by rubenskuhl** [comment]
Issues #26 and #38 are related but are possibly not the only changes required. Current error with PHP 5.6 is:
"Error connecting to tls://epp.registro.br:700: (code 0)"

**Comment by rubenskuhl** [comment]
PHP 5.5 reached end of life 21 Jul 2016:
https://secure.php.net/supported-versions.php

**Comment by rubenskuhl** [comment]
WHMCS 7, in beta as of Aug 10 2016, will require PHP 5.6; support for PHP 7.0 in WHMCS might come after the first release.

**Comment by faelp22** [comment]
Hello everyone, I would like to help solve this problem. How can I be helpful?

**Comment by rubenskuhl** [comment]
@faelp22 , what kind of test environment you have access to ?

**Comment by faelp22** [comment]
I have a development environment with the 6.3.1 version of WHMCS and production, all with PHP 5.6.24

**Comment by rubenskuhl** [comment]
@faelp22 If you already have a working connection (including credentials) to beta.registro.br you are good to go, since the issue affects both production (epp.registro.br) and OT&E (beta.registro.br). If you don't, you can get credentials to the OT&E system using this form: http://registro.br/tecnologia/epp-formulario-homologacao.txt 
(it also requires a login at http://beta.registro.br which can also be created freely) 

Note that there is no cost and the CNPJ can be any fake number since you won't be applying for accreditation in the future.

**Comment by faelp22** [comment]
@rubenskuhl I have the production environment access credentials.
will provide the credentials to access the test environment.

**Comment by RochaNeto** [comment]
Rubens, the faelp22 is the Isael, our programmer. He will try to help me update the version.

He will need access to the beta?

**Comment by rubenskuhl** [comment]
Each service provider has its own operational policies regarding testing code in production, we don't have a say on that. What we know is that most providers prefer using the test environment. 

Remember that currently the root branch points to beta.registro.br, while the productiononly branch points to the production system.

**Comment by rubenskuhl** [comment]
WHMCS 7.0 was released, supporting PHP 7.0 and some PHP 5.x versions. 
http://docs.whmcs.com/Version_7.0_Release_Notes

**Comment by RochaNeto** [comment]
Hello everyone.

After the help of friend Rubens, we can put our module to work.

Here's the code.

**WHMCS Version 6.3.1**

/modules/registrars/registrobr/RegistroEPP/RegistroEPP.class.php

`# Use OT&E if test mode is set
        
	#$local_cert = dirname(dirname(__FILE__)).'/test-client.pem';
        
        if (!isset($moduleparams['TestMode'])) {
            $Server = 'epp.registro.br' ;
            $Options = array (
            'ssl' => array (
            'passphrase' => $moduleparams['Passphrase'],
            'local_cert' => $moduleparams['Certificate']));
        } 
        else {
            $Server = 'epp.registro.br' ;
            $Options = array (
		'ssl' => array (
			'allow_self_signed' => TRUE,
			'local_cert' => $moduleparams['Certificate'],
			'passphrase' => $moduleparams['Passphrase'],
			'verify_peer' => FALSE
		));
        }


        # Create SSL context
        $context = stream_context_create($Options) ;
        
        # Create EPP client
        $client = new Net_EPP_Client();`

**Comment by jozephbrasil** [comment]
OK! @RochaNeto, what do you do to get it working on php 5.6?

**Comment by minotaurosdmf** [comment]
@RochaNeto 

I changed the code as indicated, but I still get the message "Error connecting to tls: //epp.register.br: 700: (code 0)". Is there anything that should be performed to run code with PHP version 5.6?

Note I am using WHMCS 7.

**Comment by pablomoretto** [comment]
Dear,
Has anyone managed to run the module with whmcs 7 and php 5.6?
I am getting authentication error (2200). Via shepp I connect normally.

Thank you.

**Comment by RochaNeto** [comment]
Hello, @pablomoretto 

The Shepp is on the same server as the Whmcs?

**Comment by pablomoretto** [comment]
@RochaNeto 
Yes, on the same server.
A CentOS 6.9

Any suggestion?

**Comment by rubenskuhl** [comment]
Try using the v7 branch. It's experimental but is targeted at WHMCS 7 and up.

**Comment by rubenskuhl** [comment]
Recent commit pushed PHP version compatibility to 8.1.
