### ISSUE TITLE
This module doesn't work on WHMCS 6.3.1

### ISSUE THREAD

**Issue by jozephbrasil** [registrobr/whmcs-registrobr-epp#70]
After upgrade I always getting

Registrar Error
Error connecting to tls://epp.registro.br:700: (code 0)

**Comment by rubenskuhl** [comment]
Looks related to PHP version, not to WHMCS version. Bug #68 already listed for this.

**Comment by rubenskuhl** [comment]
WHMCS older than 7.0 is no longer supported.

**Comment by jezieltp** [comment]
Hi, Rubens!

I want use again WHMCS with registrobr's plugin.

The same error **Error connecting to tls://epp.registro.br:700: (code 0)** appear.

The version of my PHP is 5.6.30 and WHMCS is with 7.2.3 version.

I have used whmcs-registrobr-epp with branch master, downloaded from URL https://github.com/registrobr/whmcs-registrobr-epp/tree/master.

The error is ocurring in the production environment. I have maked domain register and renovations manually with shepp but i need use WHMCS. In the shepp environment no error appear.

Can you help me?

Thank's a lot!

Jeziel

**Comment by rubenskuhl** [comment]
Try the "v7" branch instead... although the solution to this problem is not very elegant at this point, it works around the issue.
