### ISSUE TITLE
Alterar os números das linhas que precisa tirar no modo este do arquivo TESTE

### ISSUE THREAD

**Issue by shid** [registrobr/whmcs-registrobr-epp#72]
Precisa alterar os números das linhas onde instrue a tirar os comentários para realizar o teste no servidor beta:

https://github.com/registrobr/whmcs-registrobr-epp/blob/master/TESTES

Outra coisa, quando é executado os casos de testes (1-4) é retornado alguma informação dizendo que o mesmo foi executado? Porque quando eu executo esse teste, somente vai para a página com as outras registradoras.

**Comment by rubenskuhl** [comment]
Related to #35
