### ISSUE TITLE
Client area no longer works after upgrade from WHMCS 7.1 to 7.3

### ISSUE THREAD

**Issue by rubenskuhl** [registrobr/whmcs-registrobr-epp#73]
Blank page appears:

Exception: exception 'RuntimeException' with message 'Unable to emit response; headers already sent' in /home/super/public_html/home/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php:31 Stack trace: #0 /home/super/public_html/home/clientarea.php(0): Zend\Diactoros\Response\SapiEmitter->emit() #1 {main}

**Comment by ciocaz** [comment]
Tive o mesmo problema quando mudei do WHMCS 7.1 oara 7.5. Eu consegui resolver este problema Comentando as linhas 31, 32 e 33 do arquivo vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php

Nos testes realizados não tive mais erros no módulo do RegistroBR, nem no WHMCS, uso a versão 5.6 do PHP. Se alguem tiver erro reporta ai.

Veja como ficou o arquivo:

```
public function emit(ResponseInterface $response, $maxBufferLevel = null)
    {
        //if (headers_sent()) {
        //    throw new RuntimeException('Unable to emit response; headers already sent');
       // }

        $response = $this->injectContentLength($response);

        $this->emitStatusLine($response);
        $this->emitHeaders($response);
        $this->flush($maxBufferLevel);
        $this->emitBody($response);
    }
```

**Comment by luizjr** [comment]
> Tive o mesmo problema quando mudei do WHMCS 7.1 para 7.5. Eu consegui resolver este problema Comentando as linhas 31, 32 e 33 do arquivo vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php
> 
> Nos testes realizados não tive mais erros no módulo do RegistroBR, nem no WHMCS, uso a versão 5.6 do PHP. Se alguém tiver erro reporta ai.
> 
> Veja como ficou o arquivo:
> 
> ```
> public function emit(ResponseInterface $response, $maxBufferLevel = null)
>     {
>         //if (headers_sent()) {
>         //    throw new RuntimeException('Unable to emit response; headers already sent');
>        // }
> 
>         $response = $this->injectContentLength($response);
> 
>         $this->emitStatusLine($response);
>         $this->emitHeaders($response);
>         $this->flush($maxBufferLevel);
>         $this->emitBody($response);
>     }
> ```

Resolveu aqui pra mim! Obrigado!

**Comment by rubenskuhl** [comment]
No sign of such issue in WHMCS 8.7.6, closing issue.
