### ISSUE TITLE
Erro área do cliente DNS não publicado

### ISSUE THREAD

**Issue by souzadavi** [registrobr/whmcs-registrobr-epp#77]
Quando o domínio esta com status diferente de publicado, e o usuário tenta acessar para editar o domínio da um erro, precisa ser tratado para evitar confusão do usuário.

**Comment by rubenskuhl** [comment]
Provavelmente seja o mesmo issue de #49 e #50. O caso que você descreve é quando o domínio ainda não completou o ciclo de registro, ou quando ele não está mais publicado por estar congelado ?

**Comment by souzadavi** [comment]
É um pouco diferente, esse erro ocorre na área do cliente, quando o usuário esta logado na área do cliente e acessa um domínio que esta com status diferente de publicado. Mas esta relacionado com a issue #86

**Comment by rubenskuhl** [comment]
Com a mudança de estratégia de registro, este issue não é mais aplicável.
