### ISSUE TITLE
2 additional fields required, only 1 should 

### ISSUE THREAD

**Issue by rubenskuhl** [registrobr/whmcs-registrobr-epp#81]
Additional fields currently requires 2 additional fields, 1 for CPF and 1 for CNPJ, but only one of those should be required. 
@brunoferreiralkn , one option is to only require 1 and detect whether it's a CPF or CNPJ.

**Comment by brunoferreiralkn** [comment]
It would be a great shortcut for the installation. But I see the module already has it implemented: https://github.com/registrobr/whmcs-registrobr-epp/blob/master/whmcs/modules/registrars/registrobr/registrobr.php#L374-L392

Am I wrong?

**Comment by rubenskuhl** [comment]
At least in my test environment it's showing two fields to fill in and requiring both...

**Comment by brunoferreiralkn** [comment]
Here in my test environment and in production we have only one field appearing. We followed the module documentation about the additional fields in this was the result.

**Comment by rubenskuhl** [comment]
Perhaps this is dependent on theme being used. Which theme are you testing with ?

**Comment by rubenskuhl** [comment]
<img width="879" alt="Captura de Tela 2023-05-06 às 12 37 09" src="https://user-images.githubusercontent.com/3913097/236633695-7ecc0629-6f8d-4bf3-8641-2ea314c02733.png">

This is what happens. Two additional fields appear, one called "Register number" and the other called "CPF ou CNPJ".

**Comment by rubenskuhl** [comment]
Gotcha. "Register Number" comes with WHMCS 8.7.2 (perhaps other versions). To remove it, this has to be added:

$additionaldomainfields[".com.br"][] = array(
"Name" => "Register Number",
"Remove" => true,
);

I will do a rewrite of additionalfields.php to include other TLDs and remove repetitions, adding this for all .br TLDs.

**Comment by rubenskuhl** [comment]
Fixed in f14a483e016f8ca4252d52f7c9aef4542ac35c65
