### ISSUE TITLE
Figure out how to keep created domain at pending state until sync or poll

### ISSUE THREAD

**Issue by ghost** [registrobr/whmcs-registrobr-epp#9]
Possible solution: Hooks.

**Comment by rubenskuhl** [comment]
One option is to call localAPI (pendingOrder), but a simpler way would be better.

**Comment by rubenskuhl** [comment]
Pending in WHMCS means something requiring Admin intervention. Perhaps keeping at Active but moving to Canceled if Polll returns that the registration failed could be better.

**Comment by rubenskuhl** [comment]
Current design strategy is to use DNS servers that answer with authority for the registration and preventing that.
