### ISSUE TITLE
Erro após instalar

### ISSUE THREAD

**Issue by souzadavi** [registrobr/whmcs-registrobr-epp#91]
Após instalar o módulo ocorre um erro de referencia no banco de dados, na coluna version_number da tabela registrobr_version

Pois a coluna chama version e não version_number. 

Precisa refatorar o código para alterar a coluna para version ao invés de version_number.

![image](https://github.com/registrobr/whmcs-registrobr-epp/assets/636225/15cc6aac-cbee-447d-b4c8-5dd0838989df)

**Comment by souzadavi** [comment]
Pra resolver o problema da coluna version na tabela registrobr_version, basta alterar o nome da coluna de version para version_number.

O script do registro.br trata isso mas as vezes o usuário não tem permissão para alterar a tabela, sendo assim apenas altere direto no banco de dados e o módulo irá carregar normalmente.

**Comment by rubenskuhl** [comment]
Nova versão não terá mais tabelas auxiliares.
