### ISSUE TITLE
Error: Error connecting to tls://beta.registro.br:700

### ISSUE THREAD

**Issue by hostbits** [registrobr/whmcs-registrobr-epp#92]
O módulo esta retornando o erro abaixo no ambiente beta.registro.br. 
`
Error: Error connecting to tls://beta.registro.br:700: (code 0)
`
![image png 0bec62eaa041f67cf56df13888e55942](https://github.com/registrobr/whmcs-registrobr-epp/assets/67746796/310c905d-361f-42a2-ac80-2b11dc63b6c5)

Executei um teste via curl e verifiquei que não existe bloqueio ao destino ou na porta 700

**Comment by srbrunoferreira** [comment]
@rubenskuhl também estou recebendo o mesmo erro. O módulo só funciona com credenciais de produção?

**Comment by rubenskuhl** [comment]
> @rubenskuhl também estou recebendo o mesmo erro. O módulo só funciona com credenciais de produção?

Não, pelo contrário, só com credenciais de homologação. O problema do OP foi resolvido então não imagino relação com o que você está tendo.

**Comment by srbrunoferreira** [comment]
@rubenskuhl, reformulando minha pergunta: o módulo só funciona com credenciais de homologação (onde os dados são reais)?

**Comment by rubenskuhl** [comment]
> @rubenskuhl, reformulando minha pergunta: o módulo só funciona com credenciais de homologação (onde os dados são reais)?

Tem um radio button na configuração que diz se é para usar as credenciais de produção ou de homologação.

**Comment by rubenskuhl** [comment]
Sem maiores dados para investigar problemas, encerrado.
